from django.db import models

# Create your models here.

class Challan(models.Model):
    ChallanNo = models.IntegerField(primary_key=True, default="0")
    Date = models.DateField()
    ChallanTo = models.CharField(max_length=150)
    Particulars = models.TextField(max_length=250)
    Quantity = models.IntegerField(default="0")

class Received_Challan(models.Model):
    ChallanNo_1 = models.IntegerField(primary_key=True, default="0")
    Date_1 = models.DateField()
    Subject = models.CharField(max_length=100)
    Particulars = models.TextField(max_length=250)
    Quantity = models.IntegerField(default="0")
    Weight = models.FloatField(default="0")
    Rate = models.FloatField(default="0")
    Total = models.FloatField(default="0")
    ChallanNo_2 = models.IntegerField(default="0")
    Date_2 = models.DateField()
    Returned_Quantity = models.IntegerField(default="0")

class Invoice(models.Model):
    InvoiceNo = models.IntegerField(primary_key=True, default="0")
    Date_1 = models.DateField()
    InvoiceTo = models.CharField(max_length=150)
    OrderNo = models.IntegerField()
    Date_2 = models.DateField()
    Particulars = models.TextField(max_length=250)
    ChallanNo = models.TextField(max_length=300)
    Quantity = models.IntegerField(default="0")
    Rate = models.FloatField(default="0")
    Amount = models.FloatField(default="0")
    GST = models.FloatField(default="0")
    Total = models.FloatField(default="0")

class Received_Invoice(models.Model):
    InvoiceNo = models.TextField(primary_key=True, default="0")
    Supplier = models.CharField(max_length=300)
    Date = models.DateField()
    Delivery_Note = models.TextField(default="-")
    Mode_Terms_Of_Payment = models.TextField(default="-")
    Supplier_Reference = models.TextField(default="-")
    Other_Reference = models.TextField(default="-")
    OrderNo = models.TextField(default="-")
    Delivery_Note_Date = models.DateField()
    Despatched_Document_No = models.TextField(default="-")   
    Despatched_Through = models.TextField(default="-")
    Terms_Of_Delivery = models.TextField(default="-")
    Particulars = models.TextField(max_length=250, default="-")
    HSN_SAC = models.FloatField(default="0")
    Quantity = models.FloatField(default="0")
    Rate = models.FloatField(default="0")
    Amount = models.FloatField(default="0")
    GST_1 = models.FloatField(default="0")
    HSN_SAC_Amount = models.FloatField(default="0")
    GST_2 = models.FloatField(default="0")
    Total = models.FloatField(default="0")
    PaidBy = models.TextField(default="-")

class Received_Purchase_Order(models.Model):
    Purchase_Order_No = models.TextField(primary_key=True, default="0")
    Date = models.DateField()
    Invoice_To = models.CharField(default="-", max_length=300)
    Ship_To = models.TextField(default="-")
    Delivery_Terms = models.TextField(default="-")
    Mode_Terms_Of_Payment = models.TextField(default="-")
    Supplier_Reference = models.TextField(default="-")
    Other_Reference = models.TextField(default="-")
    Despatched_Through = models.TextField(default="-")
    Particulars_Code = models.FloatField(default="0")
    Particulars = models.TextField(max_length=300, default="-")
    Quantity = models.FloatField(default="0")
    Rate = models.FloatField(default="0")
    Amount = models.FloatField(default="0")
    Discount = models.FloatField(default="0")
    Amount_Less_Discount = models.FloatField(default="0")
    GST = models.FloatField(default="0")
    Shipping_Handling_Charges = models.FloatField(default="0")
    Total = models.FloatField(default="0")

class Purchase_Order(models.Model):
    Purchase_Order_No = models.TextField(primary_key=True, default="0")
    Date = models.DateField()
    Order_To = models.CharField(default="-", max_length=300)
    Ship_To = models.TextField(default="-")
    Delivery_Terms = models.TextField(default="-")
    Mode_Terms_Of_Payment = models.TextField(default="-")
    Supplier_Reference = models.TextField(default="-")
    Other_Reference = models.TextField(default="-")
    Despatched_Through = models.TextField(default="-")
    Particulars_Code = models.FloatField(default="0")
    Particulars = models.TextField(max_length=300, default="-")
    Quantity = models.FloatField(default="0")
    Rate = models.FloatField(default="0")
    Amount = models.FloatField(default="0")
    Discount = models.FloatField(default="0")
    Amount_Less_Discount = models.FloatField(default="0")
    GST = models.FloatField(default="0")
    Shipping_Handling_Charges = models.FloatField(default="0")
    Total = models.FloatField(default="0")
