# Generated by Django 3.2.3 on 2021-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('ChallanNo', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('ChallanTo', models.CharField(max_length=150)),
                ('Particulars', models.TextField(max_length=250)),
                ('Quantity', models.IntegerField(default='0')),
            ],
        ),
    ]
