# Generated by Django 3.2.3 on 2021-05-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedChallan',
            fields=[
                ('ChallanNo_1', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('Date_1', models.DateField()),
                ('Subject', models.CharField(max_length=100)),
                ('Particulars', models.TextField(max_length=250)),
                ('Quantity', models.IntegerField(default='0')),
                ('Weight', models.FloatField(default='0')),
                ('Rate', models.FloatField(default='0')),
                ('Total', models.FloatField(default='0')),
                ('ChallanNo_2', models.IntegerField(default='0')),
                ('Date_2', models.DateField()),
                ('Returned_Quantity', models.FloatField(default='0')),
            ],
        ),
    ]
