# Generated by Django 3.2.3 on 2021-05-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_receivedchallan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceivedChallan',
            new_name='Received_Challan',
        ),
    ]
