# Generated by Django 3.2.3 on 2021-05-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_receivedchallan_received_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received_challan',
            name='Returned_Quantity',
            field=models.IntegerField(default='0'),
        ),
    ]
