# Generated by Django 3.2.3 on 2021-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_received_challan_returned_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceNo', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('Date_1', models.DateField()),
                ('InvoiceTo', models.CharField(max_length=150)),
                ('OrderNo', models.IntegerField()),
                ('Date_2', models.DateField()),
                ('Particulars', models.TextField(max_length=250)),
                ('ChallanNo', models.TextField(max_length=300)),
                ('Quantity', models.IntegerField(default='0')),
                ('Rate', models.FloatField(default='0')),
                ('Amount', models.FloatField(default='0')),
                ('GST', models.FloatField(default='0')),
                ('Total', models.FloatField(default='0')),
            ],
        ),
    ]
