# Generated by Django 3.2.3 on 2021-05-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_received_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('Purchase_Order_No', models.TextField(default='0', primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Order_To', models.CharField(default='-', max_length=300)),
                ('Ship_To', models.TextField(default='-')),
                ('Delivery_Terms', models.TextField(default='-')),
                ('Mode_Terms_Of_Payment', models.TextField(default='-')),
                ('Supplier_Reference', models.TextField(default='-')),
                ('Other_Reference', models.TextField(default='-')),
                ('Despatched_Through', models.TextField(default='-')),
                ('Particulars_Code', models.FloatField(default='0')),
                ('Particulars', models.TextField(default='-', max_length=300)),
                ('Quantity', models.FloatField(default='0')),
                ('Rate', models.FloatField(default='0')),
                ('Amount', models.FloatField(default='0')),
                ('Discount', models.FloatField(default='0')),
                ('Amount_Less_Discount', models.FloatField(default='0')),
                ('GST', models.FloatField(default='0')),
                ('Shipping_Handling_Charges', models.FloatField(default='0')),
                ('Total', models.FloatField(default='0')),
            ],
        ),
    ]
